version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  order-service:
    image: isatoltar45/order-service
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - 9091:9091
    depends_on:
      - rabbitmq

  email-service:
    image: isatoltar45/email-service
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - 9092:9092
    depends_on:
      - rabbitmq
